# Dockerfile.nginx

# Base NGINX image
FROM nginx:latest

# Copy self-signed certificate and key
COPY cert/server.crt /etc/nginx/
COPY cert/server.key /etc/nginx/

# Copy NGINX configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 443 for HTTPS
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
