# Dockerfile.nginx

# Base NGINX image
FROM nginx:latest

# Copy self-signed certificate and key
COPY certs/fayda-digicert-2025.pem /etc/nginx/
COPY certs/privatedigi.key /etc/nginx/

# Copy NGINX configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 443 for HTTPS
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
