# Dockerfile.nginx

# Base NGINX image
FROM nginx:latest

# Copy self-signed certificate and key
COPY cert/server.crt /etc/nginx/nginx-selfsigned.crt
COPY /certserver.key /etc/nginx/nginx-selfsigned.key

# Copy NGINX configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 443 for HTTPS
EXPOSE 443

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
