name: Test Keycloak Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        ports:
          - 8080:8080
          - 5432:5432
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start services
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for Keycloak to be ready
      run: |
        until curl -s http://localhost:8080/auth | grep "Keycloak"; do
          echo "Waiting for Keycloak to be ready..."
          sleep 5
        done

    - name: Run tests
      run: |
        # Replace this with your actual test commands
        echo "Running tests..."

    - name: Stop services
      run: |
        docker-compose down

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=src
          -X
